### ISSUE TITLE
Bandwidth Spikes when sending blocks causes packet loss and high transfer latency

### ISSUE THREAD

**Issue by TheBlueMatt** [TvdW/bitpeer#11]
You might be interested in watching one of the technical talks I've done on FIBRE, or reading http://bluematt.bitcoin.ninja/2016/07/07/relay-networks/ and http://bitcoinfibre.org/ 

Because of the design of bitpeer (sending a flood of blocks over TCP all at once), it causes packet loss spikes which, in turn, causes a significant increase in latency to send blocks. You can observe this phenomenon pretty easily if you're sitting on the other end, though if you aren't looking at wireshark/tcpdump (and are just looking at what kernel exposes to you) you wont see it.

**Comment by TvdW** [comment]
Go advertise somewhere else.

**Comment by TheBlueMatt** [comment]
Huh? I didn't mean to come off as advertising, was instead pointing out a technical issue. While things like FIBRE are more complete fixes, in order for this project to be truly low-latency you'd likely want to add compact block + XThin support, as well as limit outbound bandwidth in your software (by sending to nodes in sequence instead of in parallel). Because these are not implemented, a ton of latency is added by TCP and you end up providing blocks much slower than you otherwise would.
